// Generated by scripts/generate-wordlists.mjs. Do not edit by hand.
/** Hardcoded first-move suggestions. All members are in `answers`. */
export const OPENERS: string[] = [
  "cares",
  "cores",
  "fares",
  "bones",
  "tones",
  "tales",
  "bates",
  "lanes"
];
